// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const env = import.meta.env;

export const SUPABASE_URL = env.VITE_SUPABASE_URL || env.NEXT_PUBLIC_SUPABASE_URL;
export const SUPABASE_PUBLISHABLE_KEY = env.VITE_SUPABASE_PUBLISHABLE_KEY || env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing Supabase environment configuration');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Safely get localStorage only if in browser environment
const getStorage = () => {
  if (typeof window !== 'undefined' && typeof window.localStorage !== 'undefined') {
    try {
      const testKey = '__storage_test__';
      window.localStorage.setItem(testKey, 'test');
      window.localStorage.removeItem(testKey);
      return window.localStorage;
    } catch (e) {
      return undefined;
    }
  }
  return undefined;
};

// NOTE: The auto-generated Database types only cover a subset of the live schema
// (tables like cash_receipts, lcl_template_* are missing). The client is cast to
// `Database` but runtime queries may reference tables not in the type definitions.
// TODO: Regenerate types with `supabase gen types typescript` to remove this cast.
const supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getStorage(),
    storageKey: 'sb-auth-token',
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'x-client-info': 'supabase-js/web',
    },
  },
});

export { supabaseClient as supabase };
