// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables for Supabase credentials
export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://eubrvlzkvzevidivsfha.supabase.co';
export const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1YnJ2bHprdnpldmlkaXZzZmhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNjA4NTgsImV4cCI6MjA3MzYzNjg1OH0.ni7Ogq-dKLvnCDzi8KvUVG2c1P7s0qY4xdF4AuvKwKk';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Safely get localStorage only if in browser environment
const getStorage = () => {
  if (typeof window !== 'undefined' && typeof window.localStorage !== 'undefined') {
    try {
      const testKey = '__storage_test__';
      window.localStorage.setItem(testKey, 'test');
      window.localStorage.removeItem(testKey);
      return window.localStorage;
    } catch (e) {
      return undefined;
    }
  }
  return undefined;
};

// NOTE: The auto-generated Database types only cover a subset of the live schema
// (tables like cash_receipts, lcl_template_* are missing). The client is cast to
// `Database` but runtime queries may reference tables not in the type definitions.
// TODO: Regenerate types with `supabase gen types typescript` to remove this cast.
const supabaseClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getStorage(),
    storageKey: 'sb-auth-token',
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  global: {
    headers: {
      'x-client-info': 'supabase-js/web',
    },
  },
});

export { supabaseClient as supabase };
